[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<main.cpp> -<2d_gantry.cpp>
monitor_speed = 115200
lib_deps =
    waspinator/AccelStepper @ ^1.64

[env:2d]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<2d_gantry.cpp> -<main.cpp>
monitor_speed = 115200
lib_deps = waspinator/AccelStepper @ ^1.64

